# Generated by Django 2.1 on 2019-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190605_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='date_published',
            new_name='tutorial_published',
        ),
    ]
