# Generated by Django 2.1 on 2019-06-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190609_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name_plural': 'Tutorials'},
        ),
    ]
