# Generated by Django 2.1 on 2019-06-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190609_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
    ]
