# Generated by Django 2.1 on 2019-06-09 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date pubished'),
        ),
    ]
