# Generated by Django 2.1 on 2019-06-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190609_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_category',
            new_name='tutorial_slug',
        ),
    ]
